# @package _group_
# routes group are for traffic density empty, low, medium, high

# - env_id: CogMod-v0
#   env_configs:
#     carla_map: Town04
#     routes_group: empty
#     weather_group: simple

- env_id: CogMod-v0
  env_configs:
    carla_map: Town04
    routes_group: low
    weather_group: simple

- env_id: CogMod-v0
  env_configs:
    carla_map: Town04
    routes_group: medium
    weather_group: simple

- env_id: CogMod-v0
  env_configs:
    carla_map: Town04
    routes_group: high
    weather_group: simple

# - env_id: CogMod-v0
#   env_configs:
#     carla_map: Town05
#     routes_group: empty
#     weather_group: simple

- env_id: CogMod-v0
  env_configs:
    carla_map: Town05
    routes_group: low
    weather_group: simple

- env_id: CogMod-v0
  env_configs:
    carla_map: Town05
    routes_group: medium
    weather_group: simple

- env_id: CogMod-v0
  env_configs:
    carla_map: Town05
    routes_group: high
    weather_group: simple